export enum UIActionTypes {
  SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH',
}

export enum UserActions {
  LOGIN_USER = 'LOGIN_USER',
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR = 'LOGIN_USER_ERROR',

  REFRESH_USER_TOKEN = 'REFRESH_USER_TOKEN',
  REFRESH_USER_TOKEN_SUCCESS = 'REFRESH_USER_TOKEN_SUCCESS',
  REFRESH_USER_TOKEN_ERROR = 'REFRESH_USER_TOKEN_ERROR',

  LOGOUT_USER = 'LOGOUT_USER',

  GET_USER_DATA = 'GET_USER_DATA',
  GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR',
}

export enum LibraryActions {
  SET_LIBRARY_DATA = 'SET_LIBRARY_DATA',
}
